### ISSUE TITLE
这个地方。。。要不改改。。。

### ISSUE THREAD

**Issue by wayslog** [zhangzhishan/traxex#3]
https://github.com/zhangzhishan/traxex/blob/943b3c925b53d081bdd308c726fa897d8b6a262a/src/download.rs#L244-L258

![power](https://user-images.githubusercontent.com/8586449/62705658-65bb3c00-ba20-11e9-832b-4526d4c845be.jpeg)

**Comment by zhangzhishan** [comment]
fixed. #4
